drop table if exists person CASCADE;

create table person
(
    id      integer generated by default as identity,
    age     integer not null,
    name    varchar(255),
    surname varchar(255),
    primary key (id)
)