drop table if exists person CASCADE;

create table person
(
    id            integer generated by default as identity,
    creation_date DATE    not null,
    name          varchar(255),
    age           integer not null,
    is_legal      boolean,
    primary key (id)
)